"""Dota 2 with Large Scale Deep Reinforcement Learning -- OpenAI Five (Berner et al., OpenAI 2019).

  the system      PPO with GAE on a 4096-unit LSTM (one network copy per hero), self-play, ~1-3 million timesteps per
                  batch, asynchronous rollout workers and optimizer GPUs, 10 months, 770 +- 50 PFlops/s-days
  surgery         change the network / observations / actions WITHOUT restarting: build a new model that computes the
                  same function (Net2Net-style): new hidden units get random incoming weights and ZERO outgoing
                  weights; new observations get ZERO weights; the LSTM 2048 -> 4096 widening needed small random
                  weights instead (no exact separation in a recurrent layer)
  data quality    staleness (data generated by parameters N versions old) and sample reuse (each sample used k times)
                  slow learning sharply; larger batches speed it up, but sublinearly
  team spirit     r_i = (1 - tau) rho_i + tau mean(rho): low tau early (less gradient noise), annealed to tau = 1

This file implements surgery operations on a small MLP policy (exact and approximate), a PPO + GAE learner on the
vectorised CartPole from paper 095, the paper's data-quality ablations (batch size, staleness, sample reuse) at toy
scale, a 'surgery vs restart' run on an environment that gains new observations over time, and a team-spirit toy.
"""

import importlib.util
from pathlib import Path

import numpy as np

_p = Path(__file__).resolve().parents[1] / "095-Salimans-et-al-2017-Evolution-Strategies" / "es.py"
_spec = importlib.util.spec_from_file_location("es095", _p)
ES = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ES)
CartPole = ES.CartPole

# ----------------------------------------------------------------------------------------------- a small MLP policy

def init_mlp(d_in, hidden, d_out, rng, scale=1.0):
    return {"W1": rng.normal(0, scale / np.sqrt(d_in), (d_in, hidden)), "b1": np.zeros(hidden),
            "W2": rng.normal(0, scale / np.sqrt(hidden), (hidden, d_out)), "b2": np.zeros(d_out)}


def mlp_forward(p, X):
    h = np.tanh(X @ p["W1"] + p["b1"])
    return h, h @ p["W2"] + p["b2"]


def softmax(z):
    z = z - z.max(-1, keepdims=True)
    e = np.exp(z)
    return e / e.sum(-1, keepdims=True)

# ----------------------------------------------------------------------------------------------- surgery

def surgery_widen(p, new_hidden, rng, scale=1.0):
    """Eq. (6): grow the hidden layer. New W1 columns / b1 entries random (break symmetry), new W2 rows ZERO, so the
    next layer ignores the new units and the function is unchanged."""
    d_in, h = p["W1"].shape
    q = {k: v.copy() for k, v in p.items()}
    q["W1"] = np.hstack([p["W1"], rng.normal(0, scale / np.sqrt(d_in), (d_in, new_hidden - h))])
    q["b1"] = np.r_[p["b1"], rng.normal(0, 0.1, new_hidden - h)]
    q["W2"] = np.vstack([p["W2"], np.zeros((new_hidden - h, p["W2"].shape[1]))])
    return q


def surgery_add_inputs(p, n_new):
    """Eq. (9): new observation features get ZERO weights -- the same game state gives the same action probabilities."""
    q = {k: v.copy() for k, v in p.items()}
    q["W1"] = np.vstack([p["W1"], np.zeros((n_new, p["W1"].shape[1]))])
    return q


def surgery_widen_recurrent(p, new_hidden, rng, small=0.01):
    """The LSTM case: in a recurrent layer new units feed back into the old ones, so zero outgoing weights would keep
    them symmetric forever and random ones change the function. OpenAI used SMALL random weights. Simulated here on
    the MLP by giving the new units small random outgoing weights."""
    q = surgery_widen(p, new_hidden, rng)
    h = p["W2"].shape[0]
    q["W2"][h:] = rng.normal(0, small, q["W2"][h:].shape)
    return q


def max_policy_change(p, q, X, pad=0):
    """Largest change in action probabilities over the states X (q may take `pad` extra zero-valued inputs)."""
    Xq = np.hstack([X, np.zeros((len(X), pad))]) if pad else X
    return float(np.abs(softmax(mlp_forward(p, X)[1]) - softmax(mlp_forward(q, Xq)[1])).max())

# ----------------------------------------------------------------------------------------------- PPO + GAE on CartPole

def features(s):
    return s * np.array([1.0, 1.0, 5.0, 1.0])                         # angle rescaled; MLP input


def rollout(policy, n_envs, rng, extra_obs=None):
    """Play n_envs CartPole episodes in a batch with a stochastic 2-action policy. Returns per-step arrays
    (obs, actions, log-probs, rewards, alive masks) and the episode returns."""
    env = CartPole(n_envs, rng)
    obs, acts, logp, rews, masks = [], [], [], [], []
    for _ in range(500):
        if not env.alive.any():
            break
        o = features(env.s)
        if extra_obs is not None:
            o = np.hstack([o, extra_obs(env.s)])
        pr = softmax(mlp_forward(policy, o)[1])
        a = (rng.random(n_envs) < pr[:, 1]).astype(int)
        al = env.alive.copy()
        r = env.step(np.where(a == 1, 1.0, -1.0))
        obs.append(o); acts.append(a); logp.append(np.log(pr[np.arange(n_envs), a] + 1e-12))
        rews.append(r); masks.append(al)
    return (np.array(obs), np.array(acts), np.array(logp), np.array(rews), np.array(masks)), np.array(rews).sum(0)


def gae(rews, values, masks, gamma=0.99, lam=0.95):
    """Generalized Advantage Estimation: A_t = sum_k (gamma lam)^k delta_{t+k}, delta_t = r_t + gamma V_{t+1} - V_t
    (episodes end when the mask turns off)."""
    T, n = rews.shape
    adv = np.zeros((T, n))
    last = np.zeros(n)
    for t in range(T - 1, -1, -1):
        next_v = values[t + 1] * masks[t + 1] if t + 1 < T else np.zeros(n)
        cont = masks[t + 1] if t + 1 < T else np.zeros(n)
        delta = rews[t] + gamma * next_v - values[t]
        last = delta + gamma * lam * cont * last
        adv[t] = last * masks[t]
    return adv, adv + values


class PPO:
    """Separate small MLPs for policy (2 logits) and value; clipped surrogate objective; manual gradients; Adam."""

    def __init__(self, d_in=4, hidden=16, seed=0, lr=1e-3, v_lr=1e-2, clip=0.2):
        rng = np.random.default_rng(seed)
        self.pi = init_mlp(d_in, hidden, 2, rng)
        self.pi["W2"] *= 0.01
        self.v = init_mlp(d_in, hidden, 1, rng)
        self.lr, self.v_lr, self.clip, self.t = lr, v_lr, clip, 0
        self.m = {k: {n: np.zeros_like(a) for n, a in net.items()} for k, net in (("pi", self.pi), ("v", self.v))}
        self.s = {k: {n: np.zeros_like(a) for n, a in net.items()} for k, net in (("pi", self.pi), ("v", self.v))}

    def _adam(self, name, net, grads):
        lr = self.lr if name == "pi" else self.v_lr
        for k in net:
            self.m[name][k] = 0.9 * self.m[name][k] + 0.1 * grads[k]
            self.s[name][k] = 0.999 * self.s[name][k] + 0.001 * grads[k] ** 2
            mh = self.m[name][k] / (1 - 0.9 ** self.t)
            vh = self.s[name][k] / (1 - 0.999 ** self.t)
            net[k] -= lr * mh / (np.sqrt(vh) + 1e-8)

    @staticmethod
    def _backprop(net, X, h, dout):
        dh = (dout @ net["W2"].T) * (1 - h ** 2)
        return {"W2": h.T @ dout, "b2": dout.sum(0), "W1": X.T @ dh, "b1": dh.sum(0)}

    def values(self, X):
        return mlp_forward(self.v, X)[1][:, 0]

    def update(self, X, A, old_logp, adv, ret, epochs=1, minibatches=4, rng=None):
        """`epochs` passes over the batch = the sample reuse."""
        rng = rng or np.random.default_rng(0)
        adv = (adv - adv.mean()) / (adv.std() + 1e-8)
        n = len(A)
        for _ in range(epochs):
            for idx in np.array_split(rng.permutation(n), minibatches):
                self.t += 1
                h, z = mlp_forward(self.pi, X[idx])
                pr = softmax(z)
                lp = np.log(pr[np.arange(len(idx)), A[idx]] + 1e-12)
                ratio = np.exp(lp - old_logp[idx])
                a = adv[idx]
                active = ~(((ratio > 1 + self.clip) & (a > 0)) | ((ratio < 1 - self.clip) & (a < 0)))
                # d(-ratio*a)/d logits = -a * ratio * (onehot - p) on unclipped samples
                g = -(a * ratio * active)[:, None] * (np.eye(2)[A[idx]] - pr) / len(idx)
                self._adam("pi", self.pi, self._backprop(self.pi, X[idx], h, g))
                hv, zv = mlp_forward(self.v, X[idx])
                gv = 2 * (zv[:, 0] - ret[idx])[:, None] / len(idx)
                self._adam("v", self.v, self._backprop(self.v, X[idx], hv, gv))


def train_ppo(updates=60, n_envs=16, staleness=0, reuse=1, epochs=2, seed=0, target=200, extra_obs=None, d_in=4,
              agent=None, hidden=16):
    """PPO on CartPole, one parameter VERSION per update.
      staleness k   rollouts are generated with the policy from k versions ago (asynchronous rollout workers)
      reuse k       the paper's definition: optimizer consumption / rollout production. The optimizer's work per
                    version is fixed (`epochs` passes over a buffer worth one full batch); rollouts produce only
                    n_envs / k fresh episodes per version, and the buffer keeps the last k collections -- so each
                    sample is consumed ~k times
    Returns the per-version mean training return, the first version whose mean return >= target, and the agent."""
    rng = np.random.default_rng(seed)
    agent = agent or PPO(d_in=d_in, hidden=hidden, seed=seed)
    history = [{k: v.copy() for k, v in agent.pi.items()}]
    buffer, curve, hit = [], [], None
    fresh = max(1, n_envs // reuse)
    for u in range(updates):
        actor = history[max(0, len(history) - 1 - staleness)]
        (O, Act, Lp, R, M), ep_ret = rollout(actor, fresh, rng, extra_obs)
        T = len(R)
        V = agent.values(O.reshape(-1, O.shape[-1])).reshape(T, fresh)
        adv, ret = gae(R, V, M)
        m = M.reshape(-1)
        buffer.append((O.reshape(-1, O.shape[-1])[m], Act.reshape(-1)[m], Lp.reshape(-1)[m], adv.reshape(-1)[m],
                       ret.reshape(-1)[m]))
        buffer = buffer[-reuse:]
        cat = [np.concatenate([b[i] for b in buffer]) for i in range(5)]
        agent.update(*cat, epochs=epochs, rng=rng)
        history.append({k: v.copy() for k, v in agent.pi.items()})
        history = history[-(staleness + 2):]
        curve.append(float(ep_ret.mean()))
        if hit is None and len(curve) >= 3 and np.mean(curve[-3:]) >= target:
            hit = u + 1
    return curve, hit, agent

# ----------------------------------------------------------------------------------------------- surgery vs restart

def surgery_vs_restart(stages=3, updates_per_stage=25, seed=0, target=400):
    """An environment 'under development': at each stage the observation gains features (here: a redundant noisy copy of
    the pole angle and velocity), and the network is widened. Surgery continues from the previous agent (zero weights for
    new inputs, Eq. 6 for new hidden units); restart trains a fresh agent from scratch at every stage. Report the return
    right after each change and the updates needed to reach `target` in the final environment."""
    out = {"surgery": [], "restart": []}
    agent = None
    for stage in range(stages):
        n_new = 2 * stage
        extra = (lambda s, n=n_new: np.tile(s[:, 2:4] * np.array([5.0, 1.0]), (1, n // 2))) if n_new else None
        hidden = 16 + 8 * stage
        rng = np.random.default_rng(seed + stage)
        if agent is not None:                                          # surgery
            agent.pi = surgery_widen(surgery_add_inputs(agent.pi, 2), hidden, rng)
            agent.v = surgery_widen(surgery_add_inputs(agent.v, 2), hidden, rng)
            agent.m = {k: {n: np.zeros_like(a) for n, a in net.items()} for k, net in (("pi", agent.pi), ("v", agent.v))}
            agent.s = {k: {n: np.zeros_like(a) for n, a in net.items()} for k, net in (("pi", agent.pi), ("v", agent.v))}
            agent.t = 0
        c, hit, agent = train_ppo(updates_per_stage, seed=seed + 10 * stage, extra_obs=extra, d_in=4 + n_new,
                                  agent=agent, hidden=hidden, target=target)
        out["surgery"].append({"first update return": c[0], "final return": c[-1], "updates to target": hit})
        c2, hit2, _ = train_ppo(updates_per_stage, seed=seed + 10 * stage + 1, extra_obs=extra, d_in=4 + n_new,
                                hidden=hidden, target=target)
        out["restart"].append({"first update return": c2[0], "final return": c2[-1], "updates to target": hit2})
    return out

# ----------------------------------------------------------------------------------------------- team spirit

def team_spirit(tau, agents=5, steps=300, batch=32, lr=0.5, noise=1.0, seed=0):
    """Five agents each choose effort a_i ~ Bernoulli(sigmoid(theta_i)). Raw individual reward
    rho_i = 0.4 a_i + (team bonus 2.0 if >= 4 agents made the effort) / 5 + N(0, noise^2). Each agent runs REINFORCE on
    its team-spirit reward r_i = (1 - tau) rho_i + tau mean(rho); we track the TEAM's mean reward. Also returns the
    per-agent gradient signal-to-noise ratio |E g| / std(g) at the start (higher = cleaner credit assignment)."""
    rng = np.random.default_rng(seed)
    theta = np.full(agents, -1.0)
    curve, snr0 = [], None
    for t in range(steps):
        p = 1 / (1 + np.exp(-theta))
        a = (rng.random((batch, agents)) < p).astype(float)
        bonus = 2.0 * (a.sum(1) >= 4)
        rho = 0.4 * a + bonus[:, None] / agents + noise * rng.standard_normal((batch, agents))
        r = (1 - tau) * rho + tau * rho.mean(1, keepdims=True)
        g = (r - r.mean(0)) * (a - p)
        if t == 0:
            big = 20000                                                # SNR measured on a large separate batch
            ab = (rng.random((big, agents)) < p).astype(float)
            rb = 0.4 * ab + 2.0 * (ab.sum(1) >= 4)[:, None] / agents + noise * rng.standard_normal((big, agents))
            rb = (1 - tau) * rb + tau * rb.mean(1, keepdims=True)
            gb = (rb - rb.mean(0)) * (ab - p)
            snr0 = float(np.mean(np.abs(gb.mean(0)) / gb.std(0)))
        theta += lr * g.mean(0)
        curve.append(float(rho.mean()))
    return curve, snr0


REPORTED = {
    "result": "defeated the Dota 2 world champions (Team OG) 2-0 in a best-of-three on April 13 2019; in the public Arena "
              "it won 7,215 of 7,257 games (99.4%) against 3,193 teams (3,140 of the wins were abandoned games; 29 teams "
              "won a total of 42 games)",
    "scale": "10 months of training, 770 +- 50 PFlops/s-days; batches of ~1-3 million timesteps (LSTM windows of 16); "
             "vs AlphaGo 50-150x larger batch, 20x larger model, 25x longer training",
    "model": "single-layer 4096-unit LSTM (84% of the parameters), one copy per hero; PPO with GAE (lambda 0.95); Adam; "
             "acts every 4th frame (~20,000 moves per game); 8,000-80,000 actions per step; 17 of 117 heroes",
    "surgery": "over twenty surgeries in 10 months; new hidden units: random incoming, zero outgoing weights (Eq. 6); new "
               "observations: zero weights (Eq. 9); LSTM 2048 -> 4096 with small random weights",
    "Rerun": "trained from scratch on the final environment: 2 months, 150 +- 5 PFlops/s-days (~20% of OpenAI Five's "
             "compute), reached > 98% win rate against the final OpenAI Five; restarting after each of ~20 surgeries "
             "would have taken ~40 months instead of 10",
    "batch size": "Rerun's batch (983k timesteps) trained ~2.5x faster than 123k early in training -- sublinear speedup",
    "data quality": "staleness of ~8 versions causes significant slowdowns; final system targets staleness 0-1; "
                    "sample reuse of 2-3 can cause a 2x slowdown and 8 may prevent learning a competent policy; target ~1",
    "team spirit": "r_i = (1 - tau) rho_i + tau mean(rho); low team spirit reduces gradient variance early; annealed "
                   "0.3 -> 1.0",
    "reaction time": "217 ms on average (typical human visual reaction ~250 ms)",
}
